import {
  NAVIGATION_TOKEN_START,
  APP_NAVIGATION_START,
  NAVIGATION_TOKEN_CANDIDATE,
  APP_NAVIGATION_CANDIDATE,
  NAVIGATION_TOKEN_MANGER,
  APP_NAVIGATION_MANGER,
} from './tokens/NavToken';

export const CORE_PROVIDERS = [
  {
    provide: NAVIGATION_TOKEN_START,
    useValue: APP_NAVIGATION_START,
  },
  {
    provide: NAVIGATION_TOKEN_CANDIDATE,
    useValue: APP_NAVIGATION_CANDIDATE,
  },
  {
    provide: NAVIGATION_TOKEN_MANGER,
    useValue: APP_NAVIGATION_MANGER,
  },
];
